services:
  keycloak.auth.api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: Keycloak.Auth.Api
    build:
      context: .
      dockerfile: WebApi/Dockerfile   
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres                      
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak  
      - KC_DB_USERNAME=keycloak             
      - KC_DB_PASSWORD=password             
    volumes:
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - 18080:8080
    depends_on:
      - postgres 

  postgres:
    image: postgres:15                      
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak                
      - POSTGRES_USER=keycloak              
      - POSTGRES_PASSWORD=password          
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
  
volumes:
  postgres_data: